/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/views/**/*.html.erb',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/javascript/**/*.jsx',
    './app/javascript/**/*.ts',
    './app/javascript/**/*.tsx',
  ],
  theme: {
    extend: {
      colors: {
        'pinterest-red': '#e60023',
        'green-700': '#103c25',
        'green-700-hover': '#0b2819',
        'plum-black': '#211922',
        'olive-gray': '#62625b',
        'warm-silver': '#91918c',
        'focus-blue': '#435ee5',
        'performance-purple': '#6845ab',
        'recommendation-purple': '#7e238b',
        'link-blue': '#2b48d4',
        'facebook-blue': '#0866ff',
        'pressed-blue': '#617bff',
        'sand-gray': '#e5e5e0',
        'warm-light': '#e0e0d9',
        'warm-wash': 'hsla(60, 20%, 98%, 0.5)', // Note: hsla might need custom handling in CSS
        'fog': '#f6f6f3',
        'border-disabled': '#c8c8c1',
        'hover-gray': '#bcbcb3',
        'dark-surface': '#33332e',
        'error-red': '#9e0a0a',
      },
      fontFamily: {
        'pin-sans': ['"Pin Sans"', '-apple-system', 'system-ui', 'Segoe UI', 'Roboto', 'Oxygen-Sans', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', 'Helvetica', '"ヒラギノ角ゴ Pro W3"', 'メイリオ', 'Meiryo', '"ＭＳ Ｐゴシック"', 'Arial'],
      },
      fontSize: {
        'display-hero': '70px',
        'section-heading': '28px',
        'body': '16px',
        'caption-bold': '14px',
        'caption': '12px',
        'button': '12px',
      },
      fontWeight: {
        '400': '400',
        '500': '500',
        '600': '600',
        '700': '700',
      },
      spacing: {
        '4': '4px',
        '6': '6px',
        '7': '7px',
        '8': '8px',
        '10': '10px',
        '11': '11px',
        '12': '12px',
        '16': '16px',
        '18': '18px',
        '20': '20px',
        '22': '22px',
        '24': '24px',
        '32': '32px',
        '80': '80px',
        '100': '100px',
      },
      borderRadius: {
        'standard': '12px',
        'button': '16px',
        'comfortable': '20px',
        'large': '28px',
        'section': '32px',
        'hero': '40px',
        'circle': '50%',
      },
    },
  },
  plugins: [],
}
